# **********************************************************************
#
# Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.5.1
#
# <auto-generated>
#
# Generated from file `KafkaConsumerClient.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy

# Start of module bfd
_M_bfd = Ice.openModule('bfd')
__name__ = 'bfd'

# Start of module bfd.kafkaconsumerclient
_M_bfd.kafkaconsumerclient = Ice.openModule('bfd.kafkaconsumerclient')
__name__ = 'bfd.kafkaconsumerclient'

if 'RetInfo' not in _M_bfd.kafkaconsumerclient.__dict__:
    _M_bfd.kafkaconsumerclient.RetInfo = Ice.createTempClass()
    class RetInfo(Ice.Object):
        def __init__(self, message='', ret=0):
            self.message = message
            self.ret = ret

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::bfd::kafkaconsumerclient::RetInfo')

        def ice_id(self, current=None):
            return '::bfd::kafkaconsumerclient::RetInfo'

        def ice_staticId():
            return '::bfd::kafkaconsumerclient::RetInfo'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_bfd.kafkaconsumerclient._t_RetInfo)

        __repr__ = __str__

    _M_bfd.kafkaconsumerclient.RetInfoPrx = Ice.createTempClass()
    class RetInfoPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.RetInfoPrx.ice_checkedCast(proxy, '::bfd::kafkaconsumerclient::RetInfo', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_bfd.kafkaconsumerclient.RetInfoPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_bfd.kafkaconsumerclient._t_RetInfoPrx = IcePy.defineProxy('::bfd::kafkaconsumerclient::RetInfo', RetInfoPrx)

    _M_bfd.kafkaconsumerclient._t_RetInfo = IcePy.defineClass('::bfd::kafkaconsumerclient::RetInfo', RetInfo, -1, (), False, False, None, (), (
        ('message', (), IcePy._t_string, False, 0),
        ('ret', (), IcePy._t_int, False, 0)
    ))
    RetInfo._ice_type = _M_bfd.kafkaconsumerclient._t_RetInfo

    _M_bfd.kafkaconsumerclient.RetInfo = RetInfo
    del RetInfo

    _M_bfd.kafkaconsumerclient.RetInfoPrx = RetInfoPrx
    del RetInfoPrx

if '_t_RetInfoSeq' not in _M_bfd.kafkaconsumerclient.__dict__:
    _M_bfd.kafkaconsumerclient._t_RetInfoSeq = IcePy.defineSequence('::bfd::kafkaconsumerclient::RetInfoSeq', (), _M_bfd.kafkaconsumerclient._t_RetInfo)

if 'KafkaConsumerClientManager' not in _M_bfd.kafkaconsumerclient.__dict__:
    _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager = Ice.createTempClass()
    class KafkaConsumerClientManager(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager:
                raise RuntimeError('bfd.kafkaconsumerclient.KafkaConsumerClientManager is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::bfd::kafkaconsumerclient::KafkaConsumerClientManager')

        def ice_id(self, current=None):
            return '::bfd::kafkaconsumerclient::KafkaConsumerClientManager'

        def ice_staticId():
            return '::bfd::kafkaconsumerclient::KafkaConsumerClientManager'
        ice_staticId = staticmethod(ice_staticId)

        def getUserID(self, current=None):
            pass

        def close(self, topic, group, userid, current=None):
            pass

        def closeAndDelete(self, topic, group, userid, current=None):
            pass

        def setConsumeMethod(self, group, method, current=None):
            pass

        def getStatusInfo(self, current=None):
            pass

        def get(self, topic, group, userid, current=None):
            pass

        def getFromBegin(self, topic, group, userid, current=None):
            pass

        def getPeriod(self, topic, group, date, userid, current=None):
            pass

        def getPeriodFromBegin(self, topic, group, date, userid, current=None):
            pass

        def getArray(self, topic, group, userid, seqlen, current=None):
            pass

        def getArrayFromBegin(self, topic, group, userid, seqlen, current=None):
            pass

        def getArrayPeriod(self, topic, group, date, userid, seqlen, current=None):
            pass

        def getArrayPeriodFromBegin(self, topic, group, date, userid, seqlen, current=None):
            pass

        def getBlock(self, topic, group, userid, current=None):
            pass

        def getFromBeginBlock(self, topic, group, userid, current=None):
            pass

        def getArrayBlock(self, topic, group, userid, seqlen, current=None):
            pass

        def getArrayFromBeginBlock(self, topic, group, userid, seqlen, current=None):
            pass

        def commitoffset(self, topic, group, userid, current=None):
            pass

        def hadoopGet(self, topic, group, userid, current=None):
            pass

        def hadoopGetTopicList(self, prefix, password, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_bfd.kafkaconsumerclient._t_KafkaConsumerClientManager)

        __repr__ = __str__

    _M_bfd.kafkaconsumerclient.KafkaConsumerClientManagerPrx = Ice.createTempClass()
    class KafkaConsumerClientManagerPrx(Ice.ObjectPrx):

        def getUserID(self, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getUserID.invoke(self, ((), _ctx))

        def begin_getUserID(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getUserID.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getUserID(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getUserID.end(self, _r)

        def close(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_close.invoke(self, ((topic, group, userid), _ctx))

        def begin_close(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_close.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_close(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_close.end(self, _r)

        def closeAndDelete(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_closeAndDelete.invoke(self, ((topic, group, userid), _ctx))

        def begin_closeAndDelete(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_closeAndDelete.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_closeAndDelete(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_closeAndDelete.end(self, _r)

        def setConsumeMethod(self, group, method, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_setConsumeMethod.invoke(self, ((group, method), _ctx))

        def begin_setConsumeMethod(self, group, method, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_setConsumeMethod.begin(self, ((group, method), _response, _ex, _sent, _ctx))

        def end_setConsumeMethod(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_setConsumeMethod.end(self, _r)

        def getStatusInfo(self, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getStatusInfo.invoke(self, ((), _ctx))

        def begin_getStatusInfo(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getStatusInfo.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getStatusInfo(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getStatusInfo.end(self, _r)

        def get(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_get.invoke(self, ((topic, group, userid), _ctx))

        def begin_get(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_get.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_get(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_get.end(self, _r)

        def getFromBegin(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBegin.invoke(self, ((topic, group, userid), _ctx))

        def begin_getFromBegin(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBegin.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_getFromBegin(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBegin.end(self, _r)

        def getPeriod(self, topic, group, date, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriod.invoke(self, ((topic, group, date, userid), _ctx))

        def begin_getPeriod(self, topic, group, date, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriod.begin(self, ((topic, group, date, userid), _response, _ex, _sent, _ctx))

        def end_getPeriod(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriod.end(self, _r)

        def getPeriodFromBegin(self, topic, group, date, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriodFromBegin.invoke(self, ((topic, group, date, userid), _ctx))

        def begin_getPeriodFromBegin(self, topic, group, date, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriodFromBegin.begin(self, ((topic, group, date, userid), _response, _ex, _sent, _ctx))

        def end_getPeriodFromBegin(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getPeriodFromBegin.end(self, _r)

        def getArray(self, topic, group, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArray.invoke(self, ((topic, group, userid, seqlen), _ctx))

        def begin_getArray(self, topic, group, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArray.begin(self, ((topic, group, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArray(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArray.end(self, _r)

        def getArrayFromBegin(self, topic, group, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBegin.invoke(self, ((topic, group, userid, seqlen), _ctx))

        def begin_getArrayFromBegin(self, topic, group, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBegin.begin(self, ((topic, group, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArrayFromBegin(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBegin.end(self, _r)

        def getArrayPeriod(self, topic, group, date, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriod.invoke(self, ((topic, group, date, userid, seqlen), _ctx))

        def begin_getArrayPeriod(self, topic, group, date, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriod.begin(self, ((topic, group, date, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArrayPeriod(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriod.end(self, _r)

        def getArrayPeriodFromBegin(self, topic, group, date, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriodFromBegin.invoke(self, ((topic, group, date, userid, seqlen), _ctx))

        def begin_getArrayPeriodFromBegin(self, topic, group, date, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriodFromBegin.begin(self, ((topic, group, date, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArrayPeriodFromBegin(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayPeriodFromBegin.end(self, _r)

        def getBlock(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getBlock.invoke(self, ((topic, group, userid), _ctx))

        def begin_getBlock(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getBlock.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_getBlock(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getBlock.end(self, _r)

        def getFromBeginBlock(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBeginBlock.invoke(self, ((topic, group, userid), _ctx))

        def begin_getFromBeginBlock(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBeginBlock.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_getFromBeginBlock(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getFromBeginBlock.end(self, _r)

        def getArrayBlock(self, topic, group, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayBlock.invoke(self, ((topic, group, userid, seqlen), _ctx))

        def begin_getArrayBlock(self, topic, group, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayBlock.begin(self, ((topic, group, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArrayBlock(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayBlock.end(self, _r)

        def getArrayFromBeginBlock(self, topic, group, userid, seqlen, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBeginBlock.invoke(self, ((topic, group, userid, seqlen), _ctx))

        def begin_getArrayFromBeginBlock(self, topic, group, userid, seqlen, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBeginBlock.begin(self, ((topic, group, userid, seqlen), _response, _ex, _sent, _ctx))

        def end_getArrayFromBeginBlock(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_getArrayFromBeginBlock.end(self, _r)

        def commitoffset(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_commitoffset.invoke(self, ((topic, group, userid), _ctx))

        def begin_commitoffset(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_commitoffset.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_commitoffset(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_commitoffset.end(self, _r)

        def hadoopGet(self, topic, group, userid, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGet.invoke(self, ((topic, group, userid), _ctx))

        def begin_hadoopGet(self, topic, group, userid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGet.begin(self, ((topic, group, userid), _response, _ex, _sent, _ctx))

        def end_hadoopGet(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGet.end(self, _r)

        def hadoopGetTopicList(self, prefix, password, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGetTopicList.invoke(self, ((prefix, password), _ctx))

        def begin_hadoopGetTopicList(self, prefix, password, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGetTopicList.begin(self, ((prefix, password), _response, _ex, _sent, _ctx))

        def end_hadoopGetTopicList(self, _r):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager._op_hadoopGetTopicList.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManagerPrx.ice_checkedCast(proxy, '::bfd::kafkaconsumerclient::KafkaConsumerClientManager', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_bfd.kafkaconsumerclient.KafkaConsumerClientManagerPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_bfd.kafkaconsumerclient._t_KafkaConsumerClientManagerPrx = IcePy.defineProxy('::bfd::kafkaconsumerclient::KafkaConsumerClientManager', KafkaConsumerClientManagerPrx)

    _M_bfd.kafkaconsumerclient._t_KafkaConsumerClientManager = IcePy.defineClass('::bfd::kafkaconsumerclient::KafkaConsumerClientManager', KafkaConsumerClientManager, -1, (), True, False, None, (), ())
    KafkaConsumerClientManager._ice_type = _M_bfd.kafkaconsumerclient._t_KafkaConsumerClientManager

    KafkaConsumerClientManager._op_getUserID = IcePy.Operation('getUserID', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_long, False, 0), ())
    KafkaConsumerClientManager._op_close = IcePy.Operation('close', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    KafkaConsumerClientManager._op_closeAndDelete = IcePy.Operation('closeAndDelete', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    KafkaConsumerClientManager._op_setConsumeMethod = IcePy.Operation('setConsumeMethod', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_int, False, 0)), (), ((), IcePy._t_int, False, 0), ())
    KafkaConsumerClientManager._op_getStatusInfo = IcePy.Operation('getStatusInfo', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_string, False, 0), ())
    KafkaConsumerClientManager._op_get = IcePy.Operation('get', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getFromBegin = IcePy.Operation('getFromBegin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getPeriod = IcePy.Operation('getPeriod', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getPeriodFromBegin = IcePy.Operation('getPeriodFromBegin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getArray = IcePy.Operation('getArray', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_getArrayFromBegin = IcePy.Operation('getArrayFromBegin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_getArrayPeriod = IcePy.Operation('getArrayPeriod', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_getArrayPeriodFromBegin = IcePy.Operation('getArrayPeriodFromBegin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_getBlock = IcePy.Operation('getBlock', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getFromBeginBlock = IcePy.Operation('getFromBeginBlock', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_getArrayBlock = IcePy.Operation('getArrayBlock', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_getArrayFromBeginBlock = IcePy.Operation('getArrayFromBeginBlock', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())
    KafkaConsumerClientManager._op_commitoffset = IcePy.Operation('commitoffset', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    KafkaConsumerClientManager._op_hadoopGet = IcePy.Operation('hadoopGet', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfo, False, 0), ())
    KafkaConsumerClientManager._op_hadoopGetTopicList = IcePy.Operation('hadoopGetTopicList', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), _M_bfd.kafkaconsumerclient._t_RetInfoSeq, False, 0), ())

    _M_bfd.kafkaconsumerclient.KafkaConsumerClientManager = KafkaConsumerClientManager
    del KafkaConsumerClientManager

    _M_bfd.kafkaconsumerclient.KafkaConsumerClientManagerPrx = KafkaConsumerClientManagerPrx
    del KafkaConsumerClientManagerPrx

# End of module bfd.kafkaconsumerclient

__name__ = 'bfd'

# End of module bfd
